"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabase";
import { useRouter } from "next/navigation";
import { Sparkles, Loader2 } from "lucide-react";

export default function CreateNote() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const router = useRouter();

  const handleSave = async () => {
    if (!title.trim() || !content.trim()) return;
    setIsSubmitting(true);

    try {
      // 1. Save the note
      const { data: note, error: noteError } = await supabase
        .from("notes")
        .insert([{ title, content }])
        .select()
        .single();

      if (noteError) throw noteError;

      // 2. Extract flashcards via Regex
      // Looks for <Flashcard front="front text" back="back text" />
      const regex = /<Flashcard\s+front="([^"]+)"\s+back="([^"]+)"\s*\/?>(?:<\/Flashcard>)?/g;
      let match;
      const extractedCards = [];

      while ((match = regex.exec(content)) !== null) {
        extractedCards.push({
          note_id: note.id,
          front: match[1],
          back: match[2],
        });
      }

      // 3. Save extracted flashcards if any
      if (extractedCards.length > 0) {
        const { error: flashcardError } = await supabase
          .from("flashcards")
          .insert(extractedCards);
        
        if (flashcardError) throw flashcardError;
      }

      router.push(`/notes/${note.id}`);
    } catch (error) {
      console.error("Error saving note:", error);
      alert("Failed to save note. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <h1 className="text-4xl font-extrabold text-neutral-800 dark:text-neutral-100 flex items-center gap-3">
          <Sparkles className="text-orange-400" size={36} />
          Create New Note
        </h1>
        <button
          onClick={handleSave}
          disabled={isSubmitting || !title || !content}
          className="bubbly-button bg-orange-400 text-white shadow-orange-200 disabled:opacity-50 flex items-center gap-2"
        >
          {isSubmitting && <Loader2 className="animate-spin" size={20} />}
          {isSubmitting ? "Saving..." : "Save Note"}
        </button>
      </div>

      <p className="text-lg text-neutral-600 dark:text-neutral-300 font-medium bg-orange-50 dark:bg-orange-950/20 p-4 rounded-2xl border border-orange-100 dark:border-orange-900/30">
        Paste the MDX generated by the AI here. Any <code>&lt;Flashcard&gt;</code> tags will be automatically extracted and sent to your Spaced Repetition queue!
      </p>

      <div className="space-y-6">
        <div>
          <label className="block text-sm font-bold mb-2 text-neutral-700 dark:text-neutral-300">
            Note Title
          </label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="e.g., The Laws of Thermodynamics"
            className="w-full p-4 rounded-2xl border-2 border-neutral-200 dark:border-zinc-700 focus:border-orange-400 focus:ring-4 focus:ring-orange-100 dark:focus:ring-orange-900/30 transition-all outline-none font-bold text-xl bg-white dark:bg-zinc-800"
          />
        </div>

        <div>
          <label className="block text-sm font-bold mb-2 text-neutral-700 dark:text-neutral-300">
            MDX Content
          </label>
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            placeholder="Paste your AI generated Markdown (with custom tags) here..."
            className="w-full min-h-[500px] p-6 rounded-2xl border-2 border-neutral-200 dark:border-zinc-700 focus:border-orange-400 focus:ring-4 focus:ring-orange-100 dark:focus:ring-orange-900/30 transition-all outline-none resize-y font-mono text-sm bg-white dark:bg-zinc-900 leading-relaxed"
          />
        </div>
      </div>
    </div>
  );
}
